### ISSUE TITLE
Apply_Coupons prompt is confusing

### ISSUE THREAD

**Issue by jdbean** [learn-co-curriculum/green_grocer#7]
The prompt for Apply_Coupons notes that an expected input should be:

> and a coupon for avocados that looks like this:
>
> ```ruby
> {:item => "AVOCADO", :num => 2, :cost => 5.0}
>
> ```

In practice, the test suite provides the method with an array containing a single hash in the above format. Failure to mention this array in the prompt makes the problem more complicated than it needs to be.

**Comment by Abdul-Sayed** [comment]
Agreed

**Comment by maxwellbenton** [comment]
Hi @jdbean,

Thank you for this feedback. We've updated this lesson, clarified the readme to better align with the expectations of the tests and believe this issue is resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
